### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by nmnhero** [digitalpetri/ethernet-ip#1]
The title speaks for itself. If anyone can port this library to Android platform it would be very much appreciated. As I read the code it uses a lot of Java 8 features which is not available on Android yet.

**Comment by kevinherron** [comment]
If anyone takes this on, using [retrolambda](https://github.com/orfjackal/retrolambda) and [streamsupport](http://sourceforge.net/projects/streamsupport/) might be enough that you don't have to make any code changes.

**Comment by nmnhero** [comment]
Yes I'm trying to port it right now on Android. It would be cool though if you could provide documentation or more examples on your library. :)
