### ISSUE TITLE
SymbolicTranslationService

### ISSUE THREAD

**Issue by csobsidian** [digitalpetri/ethernet-ip#10]
Would there be value to including the optional Message Router service for Symbolic Translation?

**Comment by kevinherron** [comment]
It wouldn't hurt anything, but I couldn't tell you if there's any value in adding it - I've never connected to anything that used or supported it.

**Comment by csobsidian** [comment]
I also have not used it. I wasn't sure if it was an easy way to perform segment translation for an item such as "myUdt.mySubUdt.someValue" on Logix devices. (As opposed to reading all the tags/UDTs in the processor and determining it by hand)

**Comment by kevinherron** [comment]
It would be worth double-checking, but I'm pretty sure I tried that out a while ago and the service is not supported on Logix devices.
