### ISSUE TITLE
GetInstanceAttributeListService

### ISSUE THREAD

**Issue by csobsidian** [digitalpetri/ethernet-ip#11]
There are many Logix objects that use the GetInstanceAttributeListService in order to pull attributes from all instances. Is there a reason the implementation of this service is not more generic (as opposed to only supporting the Symbol Object instances)?

**Comment by csobsidian** [comment]
Yes, the vendor specific GetInstanceAttributeListService, described in the Logix Data Access manual and implemented here for just the Symbol Object class, is available to several logix specific classes.

**Comment by kevinherron** [comment]
Okay, I've only ever seen it used with the Symbol object. If it's usable with other objects then it should be made more generic.

I have that manual but never saw any references to what else it can be used with... what are the other objects?

**Comment by csobsidian** [comment]
Off the top of my head:

0x69 Program Object
0x6B Symbol Object
0x6C Template Object
0x70 Task Object

Though not listed by attribute number, many of the attributes available via CIP are the same as those pulled with the GSV/SSV instruction and are thoroughly documented in the Logix5000 Controllers Generals Instructions Reference Manual. There are likely others not included in the list above.

**Comment by kevinherron** [comment]
@csobsidian I'm guessing you never ended up using this? Years later I'm now realizing the visibility on `GetInstanceAttributeListService.AttributesDecoder` is wrong...

**Comment by csobsidian** [comment]
@kevinherron Apologies for the late reply. It has been some time since I have had need for a java EIP implementation. Looking at the time delay between issue and PR (not a comment on you by any means, we are all busy people) I may have implemented it myself and moved on. Also, like yourself, I have to walk a line between what I am allowed and not allowed to do for open-source projects.
