### ISSUE TITLE
ListIdentity Broadcast Address

### ISSUE THREAD

**Issue by csobsidian** [digitalpetri/ethernet-ip#12]
Is there any support for sending the ListIdentity to a broadcast address?

**Comment by kevinherron** [comment]
Not built in, but it seems you could do that yourself in a few lines of code.

All you need to do is encode a ListIdentity command and then put that in the payload of a DatagramPacket and send it, yeah?

**Comment by csobsidian** [comment]
Of course, I was just making sure it wasn't implemented somewhere already.

**Comment by kevinherron** [comment]
It might be worth wrapping up into a utility class that broadcasts it, waits a configurable amount of time, then return a list of the identities that reply or something like that.

**Comment by csobsidian** [comment]
I would agree that a utility class would be helpful. Do you take pull requests?

**Comment by kevinherron** [comment]
Sure, PR away!
