### ISSUE TITLE
[Android] DINT bug

### ISSUE THREAD

**Issue by nmnhero** [digitalpetri/ethernet-ip#2]
I am doing exactly what the example code provide but the value sent to the PLC controller is not correct. Here is my code: 

     config = EtherNetIpClientConfig.builder("10.2.217.48")//"192.168.0.252"
                .setSerialNumber(0x00)
                .setVendorId(0x00)
                .setTimeout(Duration.ofSeconds(5))
                .build();

     // backplane, slot 0
    connectionPath = new EPath.PaddedEPath(
                new PortSegment(1, new byte[]{(byte) 1}));

     client = new CipClient(config, connectionPath);
     requestPath = new EPath.PaddedEPath(
                new DataSegment.AnsiDataSegment("MyDINT"));

     ByteBuf buffer = Unpooled.buffer();
     buffer.writeInt(1);
     WriteTagService serviced = new WriteTagService(
                requestPath,
                false,
                CipDataType.DINT.getCode(),
                buffer
      );
![dint](https://cloud.githubusercontent.com/assets/17043803/13069378/2a7cbbea-d4bf-11e5-9190-833ffe73fb21.jpg)

**Comment by kevinherron** [comment]
Ah, the example was written in a hurry.

The buffer needs to be little endian.

**Comment by kevinherron** [comment]
The example in the README has been updated.
