### ISSUE TITLE
Refactor the code to use the "LE" accessors instead of constructing a ByteBuffer with changed byte order

### ISSUE THREAD

**Issue by chrisdutz** [digitalpetri/ethernet-ip#21]
Currently my build is polluted by deprecation warnings as within the code we are constructing multiple LE ByteBuffers. It is suggested by the netty guys to use a normal byte buffer and use LE accessors instead. So instead of 
    
```java
    buf.readShort() 
```

we would use 
   
```java
    buf.readShortLE()
```

I think this is a lot clearer and would get rid of the deprecation warnings.

I would be happy to be of assistance in changing this.

**Comment by kevinherron** [comment]
These accessors don't exist in Netty 4.0.x and I can't upgrade to 4.1 until a bunch of other projects higher in the classloader hierarchy at work get upgraded.

**Comment by chrisdutz** [comment]
Ah ... ok ... well in that case it's probably better not to do that right now ;-)

**Comment by kevinherron** [comment]
There's probably not harm in upgrading to the latest 4.0.x if that satisfies the enforcer plugin you mentioned.

**Comment by chrisdutz** [comment]
I tried it out and prepared a PR ready for pulling: https://github.com/digitalpetri/ethernet-ip/pull/22
