### ISSUE TITLE
Not able to read the String Values

### ISSUE THREAD

**Issue by vijaymaddi** [digitalpetri/ethernet-ip#26]
Hi Kevin , 

   Thanks For the Library. we are facing issue when we are trying to read the String value for Rockwell Rslogix 5000 PLC. 
   for example when i trying to read  the hexadecimal value from PLC is "a002ce0f0900000054657374696e672039006700390067000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"   
can you guide me to understand the hex value.

**Comment by kevinherron** [comment]
Strings are actually structures, so it helps if you understand what's actually happening when you read a structure. The [Logix 5000 Controller Data Access Manual](https://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf) covers this in detail.

A String structure has two members: LEN and DATA.

`A002` is the structure marker
`CE0F` is the structure handle
`09000000` is the LEN member
the rest is DATA member. the number of bytes will always be whatever is defined by the String type, but the ones currently "valid" are the number specified by LEN.

In this case the String is made up of the bytes `54657374696e672039`, or in ASCII `Testing 9`.

**Comment by vijaymaddi** [comment]
Hey Kevin,
    Can you give me the tool name or sample java code example to convert the hex value to the meaning full String.

**Comment by kevinherron** [comment]
```
 System.out.println(new String(new byte[]{0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x39}));
```
