### ISSUE TITLE
Wrong endian-ness

### ISSUE THREAD

**Issue by gimmi** [digitalpetri/ethernet-ip#27]
Hi,

seems that the `sinAddr` does not need to be reversed

https://github.com/digitalpetri/ethernet-ip/blob/6124a80735a16a649fe2b44b5421565d4e41468d/enip-core/src/main/java/com/digitalpetri/enip/cpf/SockAddr.java#L73

**Comment by kevinherron** [comment]
Are you suggesting that field should be read in little-endian format or that the call to reverse the order is unnecessary before `readBytes`?

**Comment by gimmi** [comment]
Hi Kevin,

I was thinking that the IP address was in the reversed order, but this seems not to be the case. Se the only thing is that the code can be simplified from this:

```java
buffer.order(ByteOrder.BIG_ENDIAN).readBytes(sinAddr);
```

to just this:

```java
buffer.readBytes(sinAddr);
```

I will close the issue because it is not really an issue :-)
