### ISSUE TITLE
Memory leak in GetAttributesAllService

### ISSUE THREAD

**Issue by danetrain** [digitalpetri/ethernet-ip#28]
When decoding a response to a GetAttributesAll request, the ByteBuf data is retained during the MessageRouterResponse decode() method (line 56), but GetAttributesAllService decodeResponse() method may throw an exception without releasing that data (line 38). I believe this is the cause of a memory leak I am seeing.

**Comment by danetrain** [comment]
Seems like you could resolve this by calling response.getData().release() prior to throwing that exception.

**Comment by danetrain** [comment]
Attached is my application's stack trace with "paranoid" leak tracing enabled. Note that the exception is thrown right before the leak is detected.

**Comment by danetrain** [comment]
com.digitalpetri.enip.cip.CipResponseException: status=0x01 [connection failure] , additional=[0x0318]
	at com.digitalpetri.enip.cip.services.GetAttributesAllService.decodeResponse(GetAttributesAllService.java:38) ~[enip-client-1.1.2.jar!/:na]
	at com.digitalpetri.enip.cip.services.GetAttributesAllService.decodeResponse(GetAttributesAllService.java:9) ~[enip-client-1.1.2.jar!/:na]
	at com.digitalpetri.enip.cip.services.UnconnectedSendService.decodeResponse(UnconnectedSendService.java:122) ~[enip-client-1.1.2.jar!/:na]
	at com.digitalpetri.enip.cip.CipClient.lambda$invokeUnconnected$2(CipClient.java:112) [enip-client-1.1.2.jar!/:na]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_191]
	at com.digitalpetri.enip.cip.CipClient.lambda$sendUnconnectedData$8(CipClient.java:201) [enip-client-1.1.2.jar!/:na]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_191]
	at com.digitalpetri.enip.EtherNetIpClient$PendingRequest.lambda$new$0(EtherNetIpClient.java:309) ~[enip-client-1.1.2.jar!/:na]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_191]
	at com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:188) ~[enip-client-1.1.2.jar!/:na]
	at com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:34) ~[enip-client-1.1.2.jar!/:na]
	at com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245) ~[enip-client-1.1.2.jar!/:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_191]

2019-02-25 15:33:37.242 ERROR 25418 --- [ntLoopGroup-2-2] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 29
#29:
	io.netty.buffer.AdvancedLeakAwareByteBuf.release(AdvancedLeakAwareByteBuf.java:61)
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
	com.digitalpetri.enip.cip.CipClient.lambda$invokeUnconnected$2(CipClient.java:131)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.cip.CipClient.lambda$sendUnconnectedData$8(CipClient.java:201)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.EtherNetIpClient$PendingRequest.lambda$new$0(EtherNetIpClient.java:309)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:188)
	com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:34)
	com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245)
	java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
#28:
	io.netty.buffer.AdvancedLeakAwareByteBuf.retain(AdvancedLeakAwareByteBuf.java:731)
	com.digitalpetri.enip.cip.structs.MessageRouterResponse.decode(MessageRouterResponse.java:56)
	com.digitalpetri.enip.cip.services.GetAttributesAllService.decodeResponse(GetAttributesAllService.java:33)
	com.digitalpetri.enip.cip.services.GetAttributesAllService.decodeResponse(GetAttributesAllService.java:9)
	com.digitalpetri.enip.cip.services.UnconnectedSendService.decodeResponse(UnconnectedSendService.java:122)
	com.digitalpetri.enip.cip.CipClient.lambda$invokeUnconnected$2(CipClient.java:112)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.cip.CipClient.lambda$sendUnconnectedData$8(CipClient.java:201)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.EtherNetIpClient$PendingRequest.lambda$new$0(EtherNetIpClient.java:309)
	java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	com.digitalpetri.enip.EtherNetIpClient.onChannelRead(EtherNetIpClient.java:188)
	com.digitalpetri.enip.EtherNetIpClient.access$500(EtherNetIpClient.java:34)
	com.digitalpetri.enip.EtherNetIpClient$EtherNetIpClientHandler.lambda$channelRead0$0(EtherNetIpClient.java:245)
	java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by kevinherron** [comment]
Yes, I think you're right. I'll push a fix for this shortly.

**Comment by danetrain** [comment]
Wow, thanks for the quick response! Much appreciated.

**Comment by kevinherron** [comment]
@danetrain I cherry-picked the commit into `dev/1.3` branch too. 

I'm going to release that branch soon - if you wouldn't mind using/testing it that would be nice.

**Comment by danetrain** [comment]
I can test it. My application is built with Maven, what's the easiest way to change the pom and pull down the latest commit as opposed to the Maven repo release 1.2?

**Comment by kevinherron** [comment]
@danetrain Add the Sonatype snapshots repo:

```
<repository>
    <id>oss-sonatype</id>
    <name>oss-sonatype</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```

Then update the version to 1.3.0-SNAPSHOT.

I just deployed so it might take a minute to resolve.

**Comment by danetrain** [comment]
Here's my dependency from the pom file:

<dependency>
    <groupId>com.digitalpetri.enip</groupId>
    <artifactId>enip-client</artifactId>
    <version>1.3.0-SNAPSHOT</version>
</dependency>

It appears to be downloading fine, but now NetBeans can't resolve references to the CipClient class. IS that groupId out of date?

**Comment by kevinherron** [comment]
Try changing the artifact id to `cip-client`. Things got shuffled around a bit.

**Comment by danetrain** [comment]
Looks like that resolved the build issue. Just passed unit and functional tests as well. I'll test for the leak and let you know in an hour or so. Standby...

**Comment by kevinherron** [comment]
@danetrain there's some new options regarding how the connection is managed (see `lazy` and `persistent` in `EtherNetIpClientConfig` and you have to explicitly call `connect()` now before using the client.

**Comment by danetrain** [comment]
I think there's still more work to do on my end. I'll get back to ASAP, but probably not until some time tomorrow.

**Comment by danetrain** [comment]
Yeah I'm seeing a lot of java.lang.Exception: not connected in my logs, but I'm calling connect() on the CipClient before using it, any tips?

**Comment by kevinherron** [comment]
Make sure it connects successfully before you use it, or if you want behavior like the previous versions set `persistent` to `true` on the config and then make sure you call `connect()` at least once before using it.

Any time you `disconnect()` you have to `connect()` again.

**Comment by danetrain** [comment]
The fix appears to resolve the memory leak issue, however my code which utilizes the CipClient class is far slower. In particular, the disconnect() call appears to hang or take an inordinate amount of time to execute. This appears to be case whether ```persistent``` is enabled or not. Any suggestions?

**Comment by kevinherron** [comment]
It may be a bug, I’ll have to look into it.

Can you reproduce it easily and reliably?

**Comment by danetrain** [comment]
Yep, it's present almost every time the code executes. I'm instantiating the ```ENIPClient``` or ```CIPClient``` object with only the ```hostname``` and ```persistent``` fields set by the builder object. In a loop, I'm using the ```GetAttributesAllService``` to retrieve data from a Controllogix PLC. Almost every time the loop executes, I can verify via print statement that the ```disconnect()``` is lagging or hanging.

**Comment by kevinherron** [comment]
@danetrain this should be fixed now

**Comment by danetrain** [comment]
Awesome, thanks. Should I bump up my pom to pull version 1.3.1 from the sonatype repo?

**Comment by kevinherron** [comment]
No, just force it to refresh 1.3.0-SNAPSHOT.

**Comment by danetrain** [comment]
Ok, just tested everything both with and without 'paranoid' leak detection enabled in the JVM and it all runs correctly. When you get a chance, could you push a new release to the Maven repo? Thanks.

**Comment by kevinherron** [comment]
@danetrain `1.3.0` has been released.

**Comment by danetrain** [comment]
Thanks!
