### ISSUE TITLE
path segment error

### ISSUE THREAD

**Issue by dmzaytsev** [digitalpetri/ethernet-ip#3]
I got an error `status=0x04 [path segment error] , additional=[0x0000]` 
when I try to query for a tag like AMR[1]
I used the code from the example https://github.com/digitalpetri/ethernet-ip/tree/master/logix-services#connected-readtagservice

it works fine for tag AMR but fail for AMR[1]

![image](https://cloud.githubusercontent.com/assets/9972909/13944736/90608c54-f029-11e5-9554-1ac73cb5cabd.png)

Could  you  please explain how to use ReadTagService for such tags?
Thanks

**Comment by kevinherron** [comment]
@dmzaytsev You need to add a `MemberId` segment containing the index to be read to the request path:

```java
PaddedEPath requestPath = new PaddedEPath(
        new AnsiDataSegment("AMR"),
        new MemberId(0)
);
```

I'll add or update one of the examples to mention this.

**Comment by dmzaytsev** [comment]
@kevinherron thank you!
what about tags like `AB1[8].13` ?

**Comment by kevinherron** [comment]
@dmzaytsev I think you'd have to mask the result from reading `AB1[8]` to get bit 13 yourself.

**Comment by dmzaytsev** [comment]
@kevinherron also is some function available to convert byte response to int or real or another type ?
I mean when I get response like `c3000200` in string representation.
first byte is a datatype, second is count of elements  and third and fourth it the int value
I can convert on my side, but maybe some function already exists

**Comment by kevinherron** [comment]
@dmzaytsev The `ByteBuf` you get from `ReadTagService` has a bunch of `getXXX()` methods you can use, but there is no general "ByteUtilities" class included as part of this library.

**Comment by dmzaytsev** [comment]
@kevinherron thanks again

**Comment by dmzaytsev** [comment]
@kevinherron one more question
Kevin, does your library support tag browsing and device browsing?
thanks

**Comment by kevinherron** [comment]
All the services you need to use while browsing are supported but the library does not do it for you. It's a pretty involved process. [This document](http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf) describes how to browse the tags in a controller and all the limitations you are supposed to adhere to.

**Comment by dmzaytsev** [comment]
@kevinherron thanks
