### ISSUE TITLE
How to run ethernet/ip client?

### ISSUE THREAD

**Issue by jnzhuang** [digitalpetri/ethernet-ip#32]
Hi. I am using ubuntu-18.04 OS. After I "git clone" and "mvn clean install", I tried `java -jar enip-client/target/enip-client-1.3.2-SNAPSHOT.jar`, but the console responds "no main manifest attribute".

I want to generate a series ethernet/ip request packets with different function codes to send to the honeypot. Can you help me? Thank you.

**Comment by kevinherron** [comment]
This is just a library, there's no client or main method for you to run. You need to write your own client using the library.

There are examples in the [main README file](https://github.com/digitalpetri/ethernet-ip/blob/master/README.md) and [Logix README file](https://github.com/digitalpetri/ethernet-ip/blob/master/logix-services/README.md) that demonstrate invoking a service.

The library implements a few of the [basic services](https://github.com/digitalpetri/ethernet-ip/tree/master/cip-core/src/main/java/com/digitalpetri/enip/cip/services) and for any additional ones you'd have to implement your own `CipService` and invoke it.

**Comment by jnzhuang** [comment]
Yes, Kevin. Thank you very much.
