### ISSUE TITLE
Example for register read and write?

### ISSUE THREAD

**Issue by thhart** [digitalpetri/ethernet-ip#34]
We want to migrate from Modbus to EtherNetIP. Is it possible to provide some examples how to read and write to device via EtherNetIP?

**Comment by kevinherron** [comment]
Are you working with a Logix family PLC or a generic ENIP device?

There's examples for Logix services but for a generic device you need to know what CIP objects and instances to read from and write to. This information would be in the documentation or EDS file for the device.

**Comment by thhart** [comment]
I am working with a generic ENIP device, but since I am not an engineer in this kind of stuff, I am not sure. It is a digital I/O device which offers readable and writable registers: http://pdb2.turck.de/en/DE/products/0000001f0003f6620003003a;jsessionid=32949F8E9B6DF264ADE884AF05E08074

**Comment by kevinherron** [comment]
What do you hope to gain by switching from Modbus to ENIP?

This library only implements class 3 explicit connections right now, which means, assuming the device supports class 3, that it's still "polling" for the data rather than being a class 1 I/O connection where the device broadcasts the data continuously.

**Comment by thhart** [comment]
We are polling the devices by default. I have some problems with the device based on Modbus, so I want to check if it is protocol related...

**Comment by kevinherron** [comment]
Ok, it looks like generally these devices use Assembly instance 103 for Inputs and 104 for Outputs.

A good place to start exploring would be using the GetAttributeSingle service:

```java
        CipClient client = ...; // not shown: set up a CipClient and call connect().get()

        // Assembly Object, Instance 103, Attribute 3 (data)
        PaddedEPath requestPath = new PaddedEPath(
            new LogicalSegment.ClassId(0x04),
            new LogicalSegment.InstanceId(103),
            new LogicalSegment.AttributeId(3)
        );

        GetAttributeSingleService service = new GetAttributeSingleService(requestPath);

        ByteBuf data = client.invoke(service).get();

        System.out.println(ByteBufUtil.hexDump(data));
```

I don't know exactly what this will look like for your device.

**Comment by thhart** [comment]
This is cool and I get some reasonable result. Thanks already for your help so far.
However I have to dig further to get the data in correct order, at least I see some data changed depending of the input state. Where are these paths specified exactly, is it vendor specific?

Input 1 set:
0000010000000500000000000000000000000000
Input 1 not set:
0000000000000500000000000000000000000000

It looks like it is really different from the Modbus output. There I have some strange data inconsistency from time to time. However it is not your Modbus library ;-)

**Comment by kevinherron** [comment]
What’s the exact model number? The EDS file should help figure out what the data is.

**Comment by kevinherron** [comment]
Oops, I see you linked to a specific model already. It looks like it has 8 universal I/O.

The EDS says the data is 10 UINT16 values:
```
0000
0100
0000
0500
0000
0000
0000
0000
0000
0000
```

If the inputs start a 0 you can see where 1 is set / not set in the data you posted.
