### ISSUE TITLE
Hangs while running

### ISSUE THREAD

**Issue by KaeporaGaebora** [digitalpetri/ethernet-ip#36]
When I run a program using this library to connect to a device, even when doing something as simple as connecting and disconnecting, there are background threads that continue to run, making the application hang.

My guess is that the netty connection was not shut down properly. Or perhaps I'm missing a shutdown command? Either way, this is going to lead to major thread leak on my server. How can I fix this?

```
EtherNetIpClientConfig config = EtherNetIpClientConfig.builder("10.20.1.1")
                .setSerialNumber(0x00)
                .setVendorId(0x00)
                .setTimeout(Duration.ofSeconds(2))
                .build();

EtherNetIpClient client = new EtherNetIpClient(config);

client.connect().get();

client.disconnect();

```

**Comment by kevinherron** [comment]
You need to call `EtherNetIpShared.releaseSharedResources()` to release the threads. This should be done during application / JVM shutdown.

**Comment by KaeporaGaebora** [comment]
Thanks for the fast response! This worked. I recommend mentioning this in the examples/documentation.

**Comment by kevinherron** [comment]
I've updated the examples in the README.
