### ISSUE TITLE
What am i doing wrong? 

### ISSUE THREAD

**Issue by andr3slelouch** [digitalpetri/ethernet-ip#46]
Hello everyone, I'm trying to follow the example in https://github.com/digitalpetri/ethernet-ip/blob/master/logix-services/README.md to connect to a PLC MicroLogix 1100, so i have to change the tag to "N7:10" because thats the tag that i want to read, but im getting this error:
[![photo-2021-02-12-12-21-37.jpg](https://i.postimg.cc/5ySbYcg9/photo-2021-02-12-12-21-37.jpg)](https://postimg.cc/kRGkzpLL)
So i don't know what am i doing wrong because thats the only line that i have modified. Any help is appreciated.
Read the source code here : https://pastebin.com/jRV1uZLe

**Comment by kevinherron** [comment]
Unfortunately these "Logix" services are for CompactLogix and ControlLogix. They do not work with MicroLogix devices, which require DF1 commands embedded in CIP via the PCCC object - not something this library implements.

**Comment by andr3slelouch** [comment]
All right :c , thank you so much for the response!
