### ISSUE TITLE
Unable to write STRUCT values

### ISSUE THREAD

**Issue by uthaman** [digitalpetri/ethernet-ip#5]
Hey Kevin, Thanks for the tool !. I do have one problem when writing STRING to ALB PLC's. I can read though. The tag type is a STRUCT x020A, do you have any example for writing Struct tag types.
Below is the tag I am trying to write.

![image](https://cloud.githubusercontent.com/assets/11169629/16348775/91df09fa-3a22-11e6-87b2-e7cac8f1c11d.png)

**Comment by uthaman** [comment]
The error I am getting is invalid tag type. This is the type PLC gave when  read :)
status=0xFF, additional=[0x2107]

**Comment by kevinherron** [comment]
`0x020A` is just the marker that indicates a structured datatype. You need to provide the structure handle when writing to a structure.

**Comment by uthaman** [comment]
do you have a example on how to do this from WriteTagService please ?

**Comment by kevinherron** [comment]
I can tell you from experience the handle of the built-in String in ControlLogix is `0x0FCE`, but in general you have to either know the handle in advance or discover it via the complicated browse process detailed in [this document](http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf).

**Comment by uthaman** [comment]
Thanks for the info Kevin, I saw 0x0FCE and modified. Now the request looks perfect as per ALB, apart from one thing. Please see the request hex dump below, I dono from where that 28 00 before a0 02 is coming, can you help?

         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 70 00 00 00 01 fc 02 10 00 00 00 00 00 00 00 00 |p...............|
|00000010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 |................|
|00000020| a1 00 04 00 01 1f 60 00 b1 00 00 00 01 00 4d 08 |......`.......M.|
|00000030| 91 0b 53 31 5f 53 63 72 65 65 6e 49 64 00 28 00 |..S1_ScreenId.(.|
|00000040| a0 02 ce 0f 08 00 77 6a 68 20 31 32 33 34       |......wjh 1234  |
+--------+-------------------------------------------------+----------------+

**Comment by kevinherron** [comment]
Why don't you show an example of the code you're trying to use here.

**Comment by uthaman** [comment]
I am using the same one from your example.

PaddedEPath WrequestPath = new PaddedEPath(
			        new AnsiDataSegment("S1_ScreenId"));
			
			String value = "wjh 1234";
			ByteBuf buffer = Unpooled.buffer().order(ByteOrder.LITTLE_ENDIAN);
			buffer.writeBytes(value.getBytes(CharsetUtil.US_ASCII));
			//buffer.writeInt(46);
			
			printByteBuf(buffer,null);
			
			WriteTagService wservice = new WriteTagService(
					WrequestPath,
			        true,
			        CipDataType.STRUCT_STRING.getCode(),
			        value.length(),
			        buffer
			);

			pool.acquire().thenAccept(connection -> {
			    CompletableFuture<Void> f = client.invokeConnected(
			            connection.getO2tConnectionId(), wservice);

			    f.whenComplete((v, ex) -> {
			        if (ex != null) {
			            ex.printStackTrace();
			        } else {
			            System.out.println("WriteTagService completed.");
			        }

			        pool.release(connection);
			    });
			});

**Comment by uthaman** [comment]
Hey that additional 28 00 was from below code I had

PaddedEPath WrequestPath = new PaddedEPath(
new AnsiDataSegment("S1_ScreenId"), new Message(0));

After removing this, that went off. 

Now getting

com.digitalpetri.enip.cip.CipResponseException: status=0xFF, additional=[0x2105]
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 70 00 00 00 01 ff 02 12 00 00 00 00 00 00 00 00 |p...............|
|00000010| 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 |................|
|00000020| a1 00 04 00 01 21 60 00 b1 00 00 00 01 00 4d 07 |.....!`.......M.|
|00000030| 91 0b 53 31 5f 53 63 72 65 65 6e 49 64 00 a0 02 |..S1_ScreenId...|
|00000040| ce 0f 08 00 77 6a 68 20 31 32 33 34             |....wjh 1234    |
+--------+-------------------------------------------------+----------------+

**Comment by uthaman** [comment]
hey kevin, any idea why this 2105 error ?

**Comment by kevinherron** [comment]
0x2105 is "General Error: Access beyond end of the object."

You should read [this document](http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf).
