### ISSUE TITLE
MultipleServicePacketService fail with MALFORMED_DATA

### ISSUE THREAD

**Issue by JensGabe** [digitalpetri/ethernet-ip#58]
I'm using MultipleServicePacketService to read multipe tags, but it fails with:
**com.digitalpetri.enip.EtherNetIpClient onChannelRead
WARNING: Received SendUnitData command with status: MALFORMED_DATA**

Reading the tags individually works fine.

Is it the PLC which does not support multiple service packets, and if so, how can I check for this?

**Comment by kevinherron** [comment]
What PLC is it? I suppose it's possible that it's not supported, but unlikely if it's a Logix device, and more likely the data is actually malformed in some way...

Can you get a Wireshark capture?

**Comment by JensGabe** [comment]
OMRON NX102-1220 v2.6

**Comment by kevinherron** [comment]
We have a product that uses this library to communicate with Omron NJ/NX series and uses MultipleServicePacketService, so I don't think that's the issue.

**Comment by JensGabe** [comment]
I'm reading mixed types, both array values (eg: _HMI_M207.Alarms[3]_ boolean, _HMI_M108.DoubleInt[1]_ integer) and structure values (_Lot_Piston.Total_production_piston_ Integer) - should this be possible?

**Comment by kevinherron** [comment]
As far as the MultipleServicePacketService is concerned, yes it should be possible, but if whether or not there is some restriction in the NX I don't know. A restriction like this is not ringing any bells with me.

**Comment by JensGabe** [comment]
Any tag count limit?

**Comment by kevinherron** [comment]
Yes, you must be careful that your total data sent does not exceed the negotiated CIP connection size... 300 tags likely does exceed that.

**Comment by kevinherron** [comment]
and by "likely" I mean "certainly" 🤣

**Comment by kevinherron** [comment]
It's 500 bytes by default, you can change it using the `connectionSize` parameter of the `DefaultCipConnectionPool`.

The NJ/NX support up to a 1994 byte connection size, I think.

It takes some annoying and difficult work to figure out how many tags fit into a request. You have to look at the length of the tag names and then all the overhead at the protocol level. Looking at Wireshark to see how the request changes from as you add/remove requests will be helpful.

**Comment by JensGabe** [comment]
Ok, at least it explains the issue, should be somewhat possible to figure out.
Again, thank you very much for the support.
