### ISSUE TITLE
Specifying an IP in a EPathSegment

### ISSUE THREAD

**Issue by MxBlinkPx** [digitalpetri/ethernet-ip#6]
I have a 1756-ENBT/A with a LOGIX5573 in Backplane Slot 0, and this works great, but the diagram I have says Slot 1 is an Ethernet connection, and I can’t seem to get the EPath right, it just times out. What is the proper way to specify an IP or am I missing something? This I what I’m trying currently:

InetAddress ip = null;
try {
      ip = InetAddress.getByName("198.137.171.14");
} catch (UnknownHostException e) {
    e.printStackTrace();
}
    byte[] bytes = ip.getAddress();
    // backplane, slot 0
    PaddedEPath connectionPath = new PaddedEPath(
                new PortSegment(1, new byte[]{(byte) 1}),   //Backplane Slot
                new PortSegment(2, bytes),  //IP
                new PortSegment(1, new byte[]{(byte) 1}));

**Comment by kevinherron** [comment]
It's just a 'PortSegment' with the bytes of the IP address as a string.

```java
int portId = 1;
String address = "127.0.0.1";
PortSegment segment = new PortSegment(portId, address.getBytes())
```

What's the full path supposed to be?

**Comment by MxBlinkPx** [comment]
That worked great, thanks.

I’m pretty new to Allen Bradley PLCS, can you tell me if there is a way to read data/build a path given these parameters:
**rack,group,slot:**  3\*2\*1
**channel:** 1
**btd address:** 1BTD113:4
**AB_PI_1_ Address:**  _0n96:240

**Comment by kevinherron** [comment]
Sorry, those parameters don't make any sense to me.
