### ISSUE TITLE
Hi Speed data logging best practice?  TagList?

### ISSUE THREAD

**Issue by ryantxu** [digitalpetri/ethernet-ip#7]
Thanks for this library -- it looks really great and seems to work with the examples in README...

Now I am trying to read a bunch of tags as fast as possible and log them.  Any suggestions on the best way to do this?

etherip sets up a TimerTask... but this can hit issues if you as for too much without enoguh time:
https://github.com/EPICSTools/etherip/blob/master/src/etherip/scan/ScanList.java

Is there some clever netty way to just keep its request buffer full?

Related question, what is the best way to read multiple tags?  The ReadTagService constructor takes elementCount, but I have not made it work with anything other than 1.

I have implemented TagList with `MultipleServicePacketService`, and that seems to work.  But I am not sure you gain anything of just multiple ReadTagService requests.

**Comment by kevinherron** [comment]
Using a `MultipleServicePacketService` to house multiple `ReadTagService` requests is the correct way to read multiple tags.

As for reading a bunch of tags as fast as possible... you'll just have to issue your MSPS request(s) as fast as possible, or as fast as your desired rate is. There's no utility in this library to do that for you.

**Comment by ryantxu** [comment]
thanks!  yes that works... not as fast as I hoped for bulk reading but i think that is the limits of EtherNetIP
