### ISSUE TITLE
com.digitalpetri.enip.cip.CipResponseException: status=0x01 [connection failure] , additional=[0x0311] for RA Micro850 PLC

### ISSUE THREAD

**Issue by prasenjith-altizon** [digitalpetri/ethernet-ip#72]
com.digitalpetri.enip.cip.CipResponseException: status=0x01 [connection failure] , additional=[0x0311] for RA Micro850 PLC.

pool.acquire().whenComplete((connection, ex) -> {
if (connection != null)
//Here the connection is getting NULL
}
The above code snippet throws the above error. Able to connect to PLC and get the PLCs Metadata

**Comment by kevinherron** [comment]
What connection path are you using? The Micro800 needs a blank one, e.g.:
```java
    // connection path is blank, no routing to backplane / slot 0
    var connectionPath = new EPath.PaddedEPath();

    var client = new CipClient(config, connectionPath);

    var connectionPool = new CipConnectionPool(
        1,
        client,
        connectionPath,
        0xFFFF
    );

    client.connect().get();
```

**Comment by prasenjith-altizon** [comment]
That was helpful. Thanks
