### ISSUE TITLE
Browse tags support

### ISSUE THREAD

**Issue by ryantxu** [digitalpetri/ethernet-ip#8]
Is there a way to list the possible tag names?  For the read/write services you need to supply a path, it would be great to discover the path problematically.

Something like:
http://automatedsolutions.com/products/dotnet/asbrowse/

It seems this may do somethign similar, but I don't see any example:
https://github.com/digitalpetri/scala-ethernet-ip/tree/master/logix-services/src/main/scala/com/digitalpetri/ethernetip/cip/logix/browsing

Thanks for any pointers!

**Comment by kevinherron** [comment]
[This document](http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf) explains how one might browse all available tags in the processor. The code you linked to was written based on that document.

**Comment by pturmel** [comment]
On 08/18/2016 03:31 PM, Kevin Herron wrote:
> This document
> <http://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm020_-en-p.pdf>
> explains how one might browse all available tags in the processor. The
> code you linked to was written based on that document.

This document leaves out one critical item when retrieving the list of
tags:  the size of each dimension of array tags.  The symbol type in
attribute #2 indicates that a tag is an array, and how many dimensions,
but nothing more.  To get the actual dimensions, read the 12-byte
attribute #8.  It contains three UDINTs of the actual dimensions (unused
subscripts are zero).

Phil

**Comment by kevinherron** [comment]
the `GetInstanceAttributeListService`, as I've implemented it, reads the dimensions in addition to the instance id and name. They are part of the `SymbolInstance` object returned.

**Comment by sushiesharma** [comment]
HI Kevin,

Using GetSymbolInstanceAttributeListService ,type field of symbolInstance class is an int. 
Could you please provide pointers on how to map it to a PLC Data Type. Do we have this documented anywhere?

**Comment by kevinherron** [comment]
@sushiesharma it's from this table in the document linked above:
![image](https://user-images.githubusercontent.com/340273/70666858-69f0a380-1c24-11ea-82a5-eb8f80f3d8bf.png)
