### ISSUE TITLE
Connecting to a 5069 processor

### ISSUE THREAD

**Issue by csobsidian** [digitalpetri/ethernet-ip#9]
I receive an error from the Connection Manager when I attempt to connect to a 5069 bulletin CompactLogix 5380 processor via your tutorial in the logix-services readme.

```
pool.acquire().whenComplete((connection, ex) -> {
    if (connection != null) {
        ...
    } else {
        ex.printStackTrace();
    }
});
```

This always fails with the connection manager passing extended error 0x0315.

I was able to fix this by changing the connectionPath constructor to

```
PaddedEPath connectionPath = new PaddedEPath();
```

and modifying the static MESSAGE_ROUTER_CP_PATH.

```
        private static final PaddedEPath MESSAGE_ROUTER_CP_PATH = new PaddedEPath(
                new ClassId(0x02),
                new InstanceId(0x01));
```

**Comment by kevinherron** [comment]
Yeah, I think it's actually anything that has firmware v28+ that doesn't work with the connection path.

We use our own CipConnectionPool implementation here at work so I never came back to update the one in the library. I'll do that soon, I have a few other changes coming up.

**Comment by kevinherron** [comment]
I've removed it, thanks for the reminder.
